apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pingtest
spec:
  selector:
    matchLabels:
      app: pingtest
  template:
    metadata:
      labels:
        app: pingtest
    spec:
      containers:
      - name: pingtest
        image: busybox
        imagePullPolicy: Always
        args:
          - sleep
          - infinity
