all:
  hosts:
    master1:
      ansible_host: 10.1.1.1
      ip: 10.1.1.1
      access_ip: 10.1.1.1
    master2:
      ansible_host: 10.1.1.2
      ip: 10.1.1.2
      access_ip: 10.1.1.2
    master3:
      ansible_host: 10.1.1.3
      ip: 10.1.1.3
      access_ip: 10.1.1.3
    worker1:
      ansible_host: 10.1.11.1
      ip: 10.1.11.1
      access_ip: 10.1.11.1
    worker2:
      ansible_host: 10.1.11.2
      ip: 10.1.11.2
      access_ip: 10.1.11.2
    worker3:
      ansible_host: 10.1.11.3
      ip: 10.1.11.3
      access_ip: 10.1.11.3
  children:
    kube-master:
      hosts:
        master1:
        master2:
    kube-node:
      hosts:
        master1:
        master2:
        master3:
        worker1:
        worker2:
        worker3:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
