---
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
  #annotations:
  #  com.illumio.pairing_key: b8c576addc28609a1a70ceb2b3cede83e802594f365fb5d309a9dd460f917317

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
      annotations:
        com.illumio.role: Web
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
  namespace: echoserver
  labels:
    app: echoserver
  annotations:
    com.illumio.role: Web
    #service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: echoserver